#!/bin/sh

interfaces=$(ip -o link show | awk -F': ' '{print $2}')
wifi_interface=$(ip -o link show | awk -F': ' '{print $2}' | grep "wl")
ethernet_interface=$(ip -o link show | awk -F': ' '{print $2}' | grep -E "^en|^eth")

# Determinar si es una máquina virtual o un sistema local
system_type=$(systemd-detect-virt)
if [ "$system_type" = "none" ]; then
    system_type="SO"
else
    system_type="VM"
fi


ip_address_wifi=$(ip addr show $wifi_interface | awk '/inet / {print $2}' | cut -d'/' -f1)
if [ -n "$ip_address_wifi" ]; then
    icon="󰤢"
    ip_address=$ip_address_wifi
fi

ip_address_ethernet=$(ip addr show $ethernet_interface | awk '/inet / {print $2}' | cut -d'/' -f1)
if [ -n "$ip_address_ethernet" ]; then
    icon="󰈀"
    ip_address=$ip_address_ethernet
fi

if [ -z "$ip_address_ethernet" ] && [ -z "$ip_address_wifi" ]; then
    ip_address="Disconnected"
    icon="󱘖"
fi

# Agregar el icono de la IP
icon="$$HOME/Documents/KaliDesign/Elementos/Iconos/ip-address.png"

echo "<img>$icon</img> <txt> $system_type   $ip_address </txt>"

# Generar el clic para ejecutar el segundo script
if [ "$ip_address" != "Disconnected" ]; then
    echo "<txtclick>bash $HOME/Documents/KaliDesign/Elementos/Dirección_IP_Copy '$ip_address'</txtclick>"
fi
